settings re-design (#19)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,14 +4,12 @@ language: python
 matrix:
     include:
       # oldest supported versions:
-      - python: 3.4
-        env: TOX_ENV=py34 PYTEST_VERSION===3.0.5
+      - python: 3.5
+        env: TOX_ENV=py35 PYTEST_VERSION===3.0.5
       # previous major versions:
-      - python: 3.4
-        env: TOX_ENV=py34 PYTEST_VERSION===3.10.1
+      - python: 3.5
+        env: TOX_ENV=py35 PYTEST_VERSION===3.10.1
       # latest:
-      - python: 3.4
-        env: TOX_ENV=py34
       - python: 3.5
         env: TOX_ENV=py35
       - python: 3.6
@@ -40,12 +38,34 @@ script:
   # end-to-end tests
   - |
     if [ $TOX_ENV != "flake8" ]; then
-      cd e2e/server_unreachable
+      cd ${TRAVIS_BUILD_DIR}/e2e/server_unreachable
       tox -e $TOX_ENV | tee tox.log
       if grep -q "exited with code 3" tox.log; then
         echo "found exit code 3"
       else
         echo "expected exit code 3"
+        exit 1
+      fi
+    fi
+  - |
+    if [ $TOX_ENV != "flake8" ]; then
+      cd ${TRAVIS_BUILD_DIR}/e2e/plugin_disabled
+      tox -e $TOX_ENV | tee tox.log
+      if grep -q "1 passed" tox.log; then
+        echo "ran successfully without plugin"
+      else
+        echo "expected 1 passed"
+        exit 1
+      fi
+    fi
+  - |
+    if [ $TOX_ENV != "flake8" ]; then
+      cd ${TRAVIS_BUILD_DIR}/e2e/collect_error
+      tox -e $TOX_ENV | tee tox.log
+      if grep -q "1 errors during collection" tox.log; then
+        echo "found collection errors"
+      else
+        echo "expected collection errors"
         exit 1
       fi
     fi
